#!/bin/bash

rm -rf dist/ build/
/usr/bin/python -m venv .venv
bin=.venv/bin
$bin/pip install build
$bin/python -m build --wheel
$bin/pip install dist/api-*.whl
$bin/pip install waitress
$bin/waitress-serve --host 0.0.0.0 --port 16385 app:app